task = "compression"
task_data_dir = "./test_data/glib"

feature_index_path = "./test_data/default.index"
dedup_index_path = "./test_data/default.dedup"
chunk_data_path = "./test_data/default.data"
chunk_meta_path = "./test_data/default.meta"
file_meta_path = "./test_data/default.file"

[feature]
type = "simhash"

[chunker]
# type = "crc-cdc"
# min_sub_chunk_size = 128
# max_sub_chunk_size = 512
# stop_mask = 63
# sub_chunk_count = 32
type = "fast-cdc"
min_chunk_size = 4096
max_chunk_size = 16384
stop_mask = 8191 # 1 << 13 - 1

[storage]
encoder = "xdelta"
cache_size = 200 #mb