task = "recover_all"
chunk_data_path = "./test_data/default.data"
chunk_meta_path = "./test_data/default.meta"
file_meta_path = "./test_data/default.file"

output_dir = "./test_data/glib2/"

[storage]
encoder = "xdelta"
cache_size = 500 #mb